language: bash
script: 
  - asdf plugin test golang $TRAVIS_BUILD_DIR --asdf-plugin-gitref $TRAVIS_COMMIT go version
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y bsdmainutils; fi
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64-graviton2
     virt: lxd
     group: edge
